'use strict';

// 常量定义
module.exports = {
  // 公共变量
  COMMON_DEBUG: true,

  // 登录窗口相关
  LOGIN_TITLE: '登录',
  LOGIN_WINDOW_SIZE_WIDTH: 350,
  LOGIN_WINDOW_SIZE_HEIGHT: 550,
  LOGIN_SUCCESS_EVENT_TOPIC: 'login-success',

  // 上传窗口相关
  UPLOADER_TITLE: '上传音乐',
  UPLOADER_WINDOW_SIZE_WIDTH: 800,
  UPLOADER_WINDOW_SIZE_HEIGHT: 600,
  UPLOADER_WINDOW_SIZE_MIN_WIDTH: 350,
  UPLOADER_WINDOW_SIZE_MIN_HEIGHT: 550,

  // 网易云音乐api
  CLOUD_MUSIC_SUCCESS_STATUS: 200,
  // 二维码状态
  CLOUD_MUSIC_SCAN_EXPIRE_STATUS: 800,
  CLOUD_MUSIC_SCAN_WAIT_STATUS: 801,
  CLOUD_MUSIC_SCAN_FINISHED_STATUS: 803,
};
